<a href="https://colab.research.google.com/github/Rodrigo-Perico/DataScience/blob/main/training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import pandas as pd

In [99]:
df = pd.read_csv("data_gas.csv")

In [100]:
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 16.6+ MB

In [102]:
type(df[df.index == 2]["DATA INICIAL"].iloc[0])

str

In [103]:
df["DATA INICIAL"] = pd.to_datetime(df["DATA INICIAL"])

In [104]:
df["DATA FINAL"] = pd.to_datetime(df["DATA FINAL"])

In [105]:
type(df["DATA INICIAL"].iloc[6])

pandas._libs.tslibs.timestamps.Timestamp

In [106]:
df["MES"] = pd.to_datetime(df["DATA FINAL"]).dt.month

In [107]:
df["ANO"] = pd.to_datetime(df["DATA FINAL"]).dt.year

In [108]:
df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MES,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021

In [109]:
pd.value_counts(df["PRODUTO"])

<ipython-input-109-67670813ebcd>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df["PRODUTO"])

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

In [110]:
df[df["PRODUTO"] == "GASOLINA COMUM"]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MES,ANO
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,5,2004
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,5,2004
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,5,2004
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,5,2004
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,5,2021

In [111]:
x = df[(df["MES"] == 8) & (df["ANO"] == 2008)].copy()

In [112]:
x["PREÇO MÉDIO REVENDA"].mean()

9.300789303079416

In [113]:
df[(df["ANO"] == 2014) & (df["MES"]==5)].groupby(["ANO", "MES"])["PREÇO MÉDIO REVENDA"].mean()

ANO   MES
2014  5      9.992992
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [114]:
df["PRODUTO"].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

In [115]:
df[(df["PRODUTO"] == "GASOLINA COMUM") & (df["PREÇO MÁXIMO REVENDA"] > 5.0)].groupby("ESTADO").first()["DATA FINAL"]

ESTADO
ACRE                  2017-09-02
ALAGOAS               2018-07-21
AMAPA                 2021-03-20
AMAZONAS              2018-04-14
BAHIA                 2018-05-26
CEARA                 2019-08-17
DISTRITO FEDERAL      2018-09-15
ESPIRITO SANTO        2018-09-15
GOIAS                 2018-06-09
MARANHAO              2021-02-13
MATO GROSSO           2018-05-26
MATO GROSSO DO SUL    2021-02-06
MINAS GERAIS          2018-02-03
PARA                  2018-01-06
PARAIBA               2021-02-06
PARANA                2021-02-20
PERNAMBUCO            2018-09-08
PIAUI                 2018-10-13
RIO DE JANEIRO        2018-01-06
RIO GRANDE DO NORTE   2021-01-30
RIO GRANDE DO SUL     2018-05-26
RONDONIA              2018-09-15
RORAIMA               2021-03-06
SANTA CATARINA        2021-02-13
SAO PAULO             2018-05-26
SERGIPE               2021-02-06
TOCANTINS             2018-08-11
Name: DATA FINAL, dtype: datetime64[ns]

In [120]:
df[(df["REGIÃO"] == 'SUL') & (df["ANO"] == 2012)]["PREÇO MÉDIO REVENDA"].mean()

9.842052564102564

In [117]:
df2 = df[df["ESTADO"] == "RIO DE JANEIRO"].copy()